# Generated by Django 5.0.7 on 2024-08-20 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('EmpName', models.CharField(max_length=25)),
                ('EmpEmail', models.EmailField(max_length=254)),
                ('EmpContact', models.CharField(max_length=20)),
                ('EmpRole', models.CharField(max_length=50)),
                ('EmpSalary', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
